version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Go to Voter
          command: cd voter
      - run:
          name: Configure env
          command: bundle install
      - rub:
          name: check around
          command: ls -al
